/**
 * Data Restoration Script
 * 
 * Restores data from CSV dumps in /home/james/kanban_frontend/Kanban-backend/DATADUMP/
 * 
 * Run with: npx ts-node prisma/restore-from-dump.ts
 *
 * If tasks/comments fail to parse (multiline fields, relationMode with spaces), run:
 *   npm run db:normalize-dump
 */

// Prisma CLI loads .env via prisma.config.ts; plain `tsx` does not — load before prisma singleton.
import 'dotenv/config';

import { prisma } from '../src/infrastructure/auth/index.js';
import { UserRole } from '../src/infrastructure/auth/prisma.js';
import * as fs from 'fs';
import * as path from 'path';

const DUMP_DIR = path.join(process.cwd(), 'prisma', 'DATADUMP');

/** Seed dump: this local-part always maps to example.com and must be system ADMIN */
const SYSTEM_ADMIN_LOCAL = 'lukaszpodlipskikontakt';

function resolveUserRole(row: Record<string, string>, anonymizedEmail: string): UserRole {
  const raw = (row.role ?? '').trim().toUpperCase();
  if (raw === 'ADMIN' || raw === 'SUPPORT' || raw === 'USER') {
    return UserRole[raw as keyof typeof UserRole];
  }
  const local = anonymizedEmail.split('@')[0] ?? '';
  if (local === SYSTEM_ADMIN_LOCAL) return UserRole.ADMIN;
  return UserRole.USER;
}

// Better Auth's hash format for password "admin1234"
// Generated by Better Auth's internal hashing function
const BETTER_AUTH_HASH = '95e21e2717da27e0b70c7a4bca082805:ca8efd7d992e51534f76a62a4801e9fed87a48f9f741e31fd805dabf4fce1abcc4cfd35085a5a1f9f76a859edbdc275189cbd13b84f3ba358eeca41bbd927d65';

// Parse CSV content — handles quoted fields containing newlines
function parseCSV(content: string): Record<string, string>[] {
  const headers = content.trim().split('\n')[0].split(',');

  const rows: string[][] = [];
  let currentRow: string[] = [];
  let currentField = '';
  let inQuotes = false;
  let idx = content.indexOf('\n');
  if (idx !== -1) idx = content.indexOf('\n', idx + 1); // skip header line

  const body = idx === -1 ? '' : content.slice(idx + 1);

  for (let i = 0; i < body.length; i++) {
    const char = body[i];
    const nextChar = body[i + 1];

    if (char === '"') {
      if (inQuotes && nextChar === '"') {
        currentField += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      currentRow.push(currentField.replace(/^"|"$/g, '').replace(/""/g, '"'));
      currentField = '';
    } else if (char === '\n' && !inQuotes) {
      currentRow.push(currentField.replace(/^"|"$/g, '').replace(/""/g, '"'));
      rows.push(currentRow);
      currentRow = [];
      currentField = '';
    } else {
      currentField += char;
    }
  }
  if (currentField || currentRow.length > 0) {
    currentRow.push(currentField.replace(/^"|"$/g, '').replace(/""/g, '"'));
    rows.push(currentRow);
  }

  return rows.map(values => {
    const record: Record<string, string> = {};
    headers.forEach((header, i) => {
      record[header] = values[i] || '';
    });
    return record;
  });
}

// Anonymize email by replacing domain with example.com
function anonymizeEmail(email: string): string {
  const [localPart] = email.split('@');
  return `${localPart}@example.com`;
}

async function restoreUsers() {
  console.log('Restoring users...');
  const content = fs.readFileSync(path.join(DUMP_DIR, 'users.csv'), 'utf-8');
  const users = parseCSV(content);
  
  for (const user of users) {
    try {
      const anonymizedEmail = anonymizeEmail(user.email);
      await prisma.user.create({
        data: {
          id: parseInt(user.id),
          name: user.name,
          surname: user.surname || null,
          email: anonymizedEmail,
          password: null,
          avatarUrl: user.avatarUrl || null,
          role: resolveUserRole(user, anonymizedEmail),
          createdAt: new Date(user.createdAt),
          updatedAt: new Date(user.updatedAt),
        },
      });
      console.log(`  Created user: ${anonymizedEmail}`);
    } catch (e) {
      console.error(`  Failed to create user ${user.email}:`, e);
    }
  }
}

async function restoreProjects() {
  console.log('Restoring projects...');
  const content = fs.readFileSync(path.join(DUMP_DIR, 'projects.csv'), 'utf-8');
  const projects = parseCSV(content);
  
  for (const project of projects) {
    try {
      await prisma.project.create({
        data: {
          id: parseInt(project.id),
          name: project.name,
          description: project.description || null,
          prefix: project.prefix,
          ownerId: parseInt(project.ownerId),
          createdAt: new Date(project.createdAt),
          updatedAt: new Date(project.updatedAt),
        },
      });
      console.log(`  Created project: ${project.name}`);
    } catch (e) {
      console.error(`  Failed to create project ${project.name}:`, e);
    }
  }
}

async function restoreProjectColumns() {
  console.log('Restoring project columns...');
  const content = fs.readFileSync(path.join(DUMP_DIR, 'project_columns.csv'), 'utf-8');
  const columns = parseCSV(content);

  for (const col of columns) {
    try {
      await prisma.projectColumn.create({
        data: {
          id: parseInt(col.id),
          name: col.name,
          projectId: parseInt(col.projectId),
          order: parseInt(col.order),
          color: col.color || null,
          type: col.type || null,
          roleType: (col.roleType as any) || null,
          description: col.description || null,
          createdAt: new Date(col.createdAt),
          updatedAt: new Date(col.updatedAt),
        },
      });
    } catch (e) {
      console.error(`  Failed to create column ${col.name}:`, e);
    }
  }
  console.log(`  Restored ${columns.length} columns`);
}

async function restoreProjectUsers() {
  console.log('Restoring project memberships...');
  const content = fs.readFileSync(path.join(DUMP_DIR, 'project_users.csv'), 'utf-8');
  const memberships = parseCSV(content);
  
  for (const mem of memberships) {
    try {
      await prisma.projectUser.create({
        data: {
          id: parseInt(mem.id),
          userId: parseInt(mem.userId),
          projectId: parseInt(mem.projectId),
          role: mem.role,
          createdAt: new Date(mem.createdAt),
          updatedAt: new Date(mem.updatedAt),
        },
      });
    } catch (e) {
      console.error(`  Failed to create membership:`, e);
    }
  }
  console.log(`  Restored ${memberships.length} memberships`);
}

async function restoreTasks() {
  console.log('Restoring tasks...');
  const content = fs.readFileSync(path.join(DUMP_DIR, 'tasks.csv'), 'utf-8');
  const tasks = parseCSV(content);
  
  for (const task of tasks) {
    try {
      await prisma.task.create({
        data: {
          id: parseInt(task.id),
          name: task.name,
          description: task.description || null,
          createdById: parseInt(task.createdById),
          assigneeId: task.assigneeId ? parseInt(task.assigneeId) : null,
          projectId: parseInt(task.projectId),
          projectColumnId: task.projectColumnId ? parseInt(task.projectColumnId) : null,
          order: parseInt(task.order),
          identifier: task.identifier,
          relationMode: task.relationMode || null,
          relationId: task.relationId ? parseInt(task.relationId) : null,
          createdAt: new Date(task.createdAt),
          updatedAt: new Date(task.updatedAt),
        },
      });
    } catch (e) {
      console.error(`  Failed to create task ${task.name}:`, e);
    }
  }
  console.log(`  Restored ${tasks.length} tasks`);
}

async function restoreTaskComments() {
  console.log('Restoring task comments...');
  const content = fs.readFileSync(path.join(DUMP_DIR, 'task_comments.csv'), 'utf-8');
  const comments = parseCSV(content);
  
  for (const comment of comments) {
    try {
      await prisma.taskComment.create({
        data: {
          id: parseInt(comment.id),
          taskId: parseInt(comment.taskId),
          userId: parseInt(comment.userId),
          content: comment.content || null,
          createdAt: new Date(comment.createdAt),
          updatedAt: new Date(comment.updatedAt),
        },
      });
    } catch (e) {
      console.error(`  Failed to create comment:`, e);
    }
  }
  console.log(`  Restored ${comments.length} comments`);
}

async function restoreTaskLogs() {
  console.log('Restoring task logs...');
  const content = fs.readFileSync(path.join(DUMP_DIR, 'task_logs.csv'), 'utf-8');
  const logs = parseCSV(content);
  
  const batchSize = 100;
  for (let i = 0; i < logs.length; i += batchSize) {
    const batch = logs.slice(i, i + batchSize);
    await Promise.all(
      batch.map(log =>
        prisma.taskLog.create({
          data: {
            id: parseInt(log.id),
            taskId: parseInt(log.taskId),
            userId: parseInt(log.userId),
            text: log.text || null,
            createdAt: new Date(log.createdAt),
            updatedAt: new Date(log.updatedAt),
          },
        }).catch(() => null)
      )
    );
    if (i % 1000 === 0) {
      console.log(`  Processed ${i}/${logs.length} logs...`);
    }
  }
  console.log(`  Restored ${logs.length} task logs`);
}

async function restoreProjectDocuments() {
  const filePath = path.join(DUMP_DIR, 'project_documents.csv');
  if (!fs.existsSync(filePath)) {
    console.log('  project_documents.csv not found, skipping');
    return;
  }
  console.log('Restoring project documents...');
  const content = fs.readFileSync(filePath, 'utf-8');
  const docs = parseCSV(content);
  
  for (const doc of docs) {
    try {
      await prisma.projectDocument.create({
        data: {
          id: parseInt(doc.id),
          projectId: parseInt(doc.projectId),
          title: doc.title,
          content: doc.content || '',
          docType: doc.docType as any,
          version: parseInt(doc.version) || 1,
          createdById: parseInt(doc.createdById),
          createdAt: new Date(doc.createdAt),
          updatedAt: new Date(doc.updatedAt),
        },
      });
    } catch (e) {
      console.error(`  Failed to create document ${doc.id}:`, e);
    }
  }
  console.log(`  Restored ${docs.length} documents`);
}

async function restoreTaskDocumentLinks() {
  const filePath = path.join(DUMP_DIR, 'task_document_links.csv');
  if (!fs.existsSync(filePath)) {
    console.log('  task_document_links.csv not found, skipping');
    return;
  }
  console.log('Restoring task document links...');
  const content = fs.readFileSync(filePath, 'utf-8');
  const links = parseCSV(content);
  
  for (const link of links) {
    try {
      await prisma.taskDocumentLink.create({
        data: {
          id: parseInt(link.id),
          projectId: parseInt(link.projectId),
          taskId: parseInt(link.taskId),
          documentId: parseInt(link.documentId),
          role: (link.role as any) || null,
          pinnedVersion: link.pinnedVersion ? parseInt(link.pinnedVersion) : null,
          createdAt: new Date(link.createdAt),
          createdBy: link.createdBy ? parseInt(link.createdBy) : null,
        },
      });
    } catch (e) {
      console.error(`  Failed to create link ${link.id}:`, e);
    }
  }
  console.log(`  Restored ${links.length} links`);
}

async function main() {
  console.log('Starting data restoration from CSV dumps...\n');
  
  console.log('Clearing existing data...');
  await prisma.taskLog.deleteMany();
  await prisma.taskComment.deleteMany();
  await prisma.task.deleteMany();
  await prisma.projectColumn.deleteMany();
  await prisma.projectUser.deleteMany();
  await prisma.project.deleteMany();
  await prisma.user.deleteMany();
  console.log('Cleared existing data\n');
  
  await restoreUsers();
  await restoreProjects();
  await restoreProjectColumns();
  await restoreProjectUsers();
  await restoreTasks();
  await restoreTaskComments();
  await restoreTaskLogs();
  await restoreProjectDocuments();
  await restoreTaskDocumentLinks();
  
  console.log('\nSetting default password for all users...');
  await prisma.$executeRaw`
    UPDATE "User" 
    SET password = ${BETTER_AUTH_HASH}
    WHERE password IS NULL
  `;
  console.log('Default password set (admin1234)');
  
  console.log('\nCreating Better Auth Account records...');
  const allUsers = await prisma.user.findMany();
  for (const user of allUsers) {
    await prisma.$executeRaw`
      INSERT INTO "Account" ("userId", "accountId", "providerId", "password", "createdAt", "updatedAt")
      VALUES (${user.id}, ${user.id.toString()}, 'credential', ${BETTER_AUTH_HASH}, NOW(), NOW())
      ON CONFLICT ("providerId", "accountId") DO NOTHING
    `;
  }
  console.log(`Created ${allUsers.length} Account records`);
  
  console.log('\n✅ Data restoration complete!');
  console.log('\nAll users can now login with: <email> / admin1234');
}

main()
  .catch((e) => {
    console.error('Restoration failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });