#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [[ ! -f .env ]]; then
  cp .env.example .env
  echo "Created .env from .env.example — edit secrets before production use."
fi

# shellcheck disable=SC1091
set -a
source .env
set +a

: "${VT_DOMAIN:?VT_DOMAIN required}"
: "${RPXY_HTTPS_PORT:?RPXY_HTTPS_PORT required}"
: "${HUB_HTTP_PORT:?HUB_HTTP_PORT required}"

PUBLIC_URL="https://${VT_DOMAIN}:${RPXY_HTTPS_PORT}"
VIBETASK_HUB_URL_DIRECT="http://127.0.0.1:${HUB_HTTP_PORT}"

# Update derived values in .env (idempotent block)
upsert_env() {
  local key="$1" value="$2" file=".env"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$file"
  else
    echo "${key}=${value}" >> "$file"
  fi
}

upsert_env PUBLIC_URL "$PUBLIC_URL"
upsert_env VITE_API_BASE_URL "$PUBLIC_URL"
upsert_env VITE_WS_BASE_URL "$PUBLIC_URL"
upsert_env BETTER_AUTH_URL "$PUBLIC_URL"
upsert_env DEVELOPMENT_FE_ORIGIN "$PUBLIC_URL"
upsert_env VIBETASK_HUB_URL "$PUBLIC_URL"

# Re-source after updates
set -a
source .env
set +a

./scripts/mkcert-init.sh
# Ensure existing certs are readable if mkcert-init skipped regeneration.
if [[ -d certs ]]; then
  chmod a+r certs/*.pem 2>/dev/null || true
fi
./scripts/render-config.sh

cat > app-hub.env <<EOF
# Generated by scripts/setup.sh — source before CLI/MCP:
#   source containers/app-hub.env
export VIBETASK_HUB_URL=${PUBLIC_URL}
export VIBETASK_HUB_URL_DIRECT=${VIBETASK_HUB_URL_DIRECT}
EOF

echo "Wrote app-hub.env (VIBETASK_HUB_URL=${PUBLIC_URL})"

if [[ "${HUB_PUBLISH_TO_HOST:-false}" == "true" ]]; then
  cat > compose.override.yaml <<EOF
services:
  hub:
    ports:
      - "127.0.0.1:\${HUB_HTTP_PORT}:\${HUB_HTTP_PORT}"
  hub-dev:
    ports:
      - "127.0.0.1:\${HUB_HTTP_PORT}:\${HUB_HTTP_PORT}"
EOF
  echo "HUB_PUBLISH_TO_HOST=true — wrote compose.override.yaml (direct hub on ${VIBETASK_HUB_URL_DIRECT})"
else
  rm -f compose.override.yaml
fi

if ! grep -q "$VT_DOMAIN" /etc/hosts 2>/dev/null; then
  echo ""
  echo "Add to /etc/hosts:"
  echo "  127.0.0.1 ${VT_DOMAIN}"
fi

check_port() {
  local port="$1"
  if ss -ltn 2>/dev/null | grep -q ":${port} "; then
    echo "WARN: port ${port} already in use on this host" >&2
  fi
}

check_port "$RPXY_HTTP_PORT"
check_port "$RPXY_HTTPS_PORT"
check_port "$POSTGRES_PORT"

echo ""
echo "Setup complete."
echo "  App URL:  ${PUBLIC_URL}"
echo "  CLI/MCP:  source app-hub.env"
echo ""
echo "Next: podman compose --profile dev up --build"
